# Generated by Django 3.2.24 on 2024-07-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardi', '0004_auto_20240713_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='marble', max_length=100),
        ),
    ]
